name: beam_PreCommit_Go

on:
  push:
    branches: ['**']
  pull_request:   
    branches: ['**']
  issue_comment:
    types: [created]
  schedule:
    - cron: '*/5 * * * *'


jobs:
  beam_PreCommit_Go:
        runs-on: [ubuntu-latest]
        name: beam_PreCommit_Go
        steps:
          - name: run goPreCommit script
            run: echo say hello standard pr

  beam_PreCommit_Go_Phrase:
#   if: ${{ github.event.issue.pull_request == 'Run Go PreCommit'}}
# if: ${{github.event.issue.pull_request}} && 
    if: ${{github.event.issue.pull_request}} || ${{github.event.comment.body == 'Run Go PreCommit'}}
    runs-on: [ubuntu-latest]
    name: beam_PreCommit_Go_Phrase
    steps:
      - name: run goPreCommit script
        run: echo say hello from comment 
